name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  Test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.12.0'
          
      - name: Install Dependencies
        run: cd ./frontend && npm install
      
      - name: Run Tests for the frontend
        run: cd ./frontend && npm test

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Install Dependencies
        run: pip install --no-cache-dir -r ./backend/requirements.txt
      
      - name: Run tests
        run: python ./backend/accounts/tests.py    

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
       
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.BACKEND_IMAGE }}
       
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.FRONTEND_IMAGE }}
    needs: Test      

  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:  
      - name: Deploy to staging
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker ps -aq && xargs docker stop
            docker-compose up -d
    needs: [Test, Build]      

  Deploy-Prod:
    runs-on: ubuntu-latest
    steps:  
      - name: Deploy to staging
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          script: |
            git clone <repository>
            docker ps -aq && xargs docker stop
            docker-compose up -d      
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.DEPLOY_TOKEN }}
          approvers: github-user
          minimum-approvals: 2
          timeout-minutes: 180
          permissions:
            issues: write
    needs: [Test, Build, Deploy-Staging] 

